databases:
  - name: grocer-ease
    user: grocer-ease
    plan: free
    region: oregon

services:
  - type: web
    name: grocer-ease
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocer-ease
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false