databases:
  - name: grocerEase
    user: bubbapang
    plan: free
    region: oregon

services:
  - type: web
    name: grocerEase
    plan: free
    region: oregon
    branch: master
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grocerEase
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false